name: Do things every 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World and Time
        run: |
          echo "$(date) Hello, world!" >> hello.txt
          cat hello.txt

      - name: Upload hello.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-file
          path: hello.txt
